### PR TITLE
Pushnotification

### PR DESCRIPTION
**Pull request by ishaque-mobikasa**
Changed some push notification issues...Added resetAll button,Removed some console logging messages

### CODE REVIEW

**Comment by tusharmobikasa** [comment]
As I checked the FCM token is coming when the user press the login button of the application but the FCM token should comes when application launches because as per the promotional notification the user will not be able to get the notifications you are restricting the notifications which is the wrong way

**Comment by tusharmobikasa** [comment]
Also there are many changes in one PR 
1 - changes of bottom app bar code
2 - remote config code
3 - push notifications code 
please make different MR's for better understanding

**Comment by ishaque-mobikasa** [comment]
> As I checked the FCM token is coming when the user press the login button of the application but the FCM token should comes when application launches because as per the promotional notification the user will not be able to get the notifications you are restricting the notifications which is the wrong way...



please check that i am storing the Token in the Firebase server with the registration email address as the key to the firebase document ..
please elaborate how is it possible to store without a user identification..
and now the app will show notifications for only loggedin user since the user cant enter into the app without logging in...
so how is it possible to show notification without the user at least once inside the app..

can you please elaborate?

**Comment by tusharmobikasa** [comment]
You need to change the logic of the application ie- if user is not logged in into the application the it should store the token to some unknown_user variable which describes that user is not registered so only to that users you can send the promotional notfications. if the user is logged in you can save that token and use by passing the value or storing at local but not calling the method again and again in this condition you can send the notification to the users who placed some order or send some payment method or any thing specific to it .

**Comment by ishaque-mobikasa** [comment]
New commits and changes..Please check that one..

**Pull request closed without merging**
